all:
		python main.py -l 20 -m 20 -i 20 -d 40

clean:
    find . -name '*.pyc' -exec rm --force {} +
    find . -name '*.pyo' -exec rm --force {} +
    find . -name '*~' -exec rm --force  {} +

run:
    python main.py -l 20 -m 20 -i 20 -d 40
